---
#####################################################################
# Project:       Juniper
# Prototype:     Monitoring and Diagnostic Frontend for CasCor Neural Network
# File Name:     .codecov.yml
# Author:        Paul Calnon
# Version:       1.0.0
#
# Date:          2025-11-03
# Last Modified: 2025-12-03
#
# License:       MIT License
# Copyright:     Copyright (c) 2024-2025 Paul Calnon
#
# Description:
#    Codecov configuration for coverage reporting and quality gates
#####################################################################

# Coverage Configuration
coverage:
  # Precision for coverage percentage
  precision: 2
  round: down
  range: 70..100

  # Status checks for PRs and commits
  status:
    # Project-level coverage requirements
    project:
      default:
        target: 80%  # Target coverage for entire project
        threshold: 5%  # Allow 5% drop without failing
        base: auto  # Compare against parent commit
        if_ci_failed: error
        informational: false

    # Patch-level coverage requirements (new code)
    patch:
      default:
        target: 60%  # New code should have 60%+ coverage
        threshold: 10%  # More lenient for patches
        base: auto
        if_ci_failed: error
        informational: false

  # Changes required for coverage status
  changes:
    default:
      target: auto
      threshold: 1%

# Comment configuration on PRs
comment:
  layout: reach,diff,flags,tree
  behavior: default  # Post new comment each time
  require_changes: false
  require_base: false
  require_head: true

# Ignore patterns (files/directories to exclude from coverage)
ignore:
  - src/tests/**  # Test files themselves
  # - src/tests/unit/implementation_script.py
  - src/tests/unit/**
  - src/tests/integration/**
  - src/tests/performance/**
  - src/tests/demo_mode/**
  - src/tests/regression/**
  - utils/**  # Utility scripts
  - scripts/**
  - prompts/**
  - notes/**
  - docs/**
  - "**/__pycache__/**"
  - "**/.pytest_cache/**"
  - reports/**
  - logs/**
  - data/**
  - images/**
  - "*.md"
  - "*.txt"
  - "*.bash"
  - "*.sh"

# Flag configurations for different test types
flags:
  unittests:
    paths:
      - src/
    carryforward: true

# Codecov behavior
codecov:
  # Require CI to pass before processing
  require_ci_to_pass: true

  # Notify configuration
  notify:
    after_n_builds: 3  # Wait for all Python version builds
    wait_for_ci: true

# GitHub Checks integration
github_checks:
  annotations: true
