#!/usr/bin/env bash
# Build a conda-tree shim that launches the cascor service UNDER py-spy.
#
# Project:     juniper-ml
# Sub-Project: ad-hoc tooling
# Author:      Paul Calnon
# Created:     2026-08-23
# Status:      ad-hoc -- one-off (residual CLI-vs-service wall gap, post-#533)
# Retire when: the residual wall-gap evidence note is merged; delete then.
# Related:     util/experiment_stack.bash (whose JUNIPER_EXP_CONDA_DIR hook this uses).
#
# WHY A SHIM AND NOT `py-spy record --pid`
# This host runs `kernel.yama.ptrace_scope = 1`, so a process may only be traced by one of its
# ANCESTORS. Verified rather than assumed: attaching py-spy to a running non-descendant returns
# "Permission Denied". There is no passwordless sudo.
#
# The direct-CLI arm is easy -- py-spy can spawn `python main.py` itself and is therefore the
# parent. The SERVICE arm is not: `experiment_stack.bash` starts uvicorn under `nohup` and then
# exits, so uvicorn is reparented away and nothing that started later can ever trace it or the
# candidate workers it forks.
#
# `env_bin()` builds every service binary path as ${CONDA_DIR}/envs/<env>/bin/<name>, and CONDA_DIR
# comes from JUNIPER_EXP_CONDA_DIR. So pointing that at a shim tree whose `uvicorn` is really
# `py-spy record ... -- <real uvicorn>` makes py-spy the parent of uvicorn, and therefore an
# ancestor of every forked candidate worker -- which is exactly the ancestry YAMA wants, and it
# survives the reparenting because py-spy itself keeps running.
#
# Everything the launcher does NOT need to profile is symlinked straight through to the real tree,
# so juniper-data and anything else behave exactly as they normally would.
#
# Usage: util/ad-hoc/2026-08-23_pyspy_conda_shim.bash <SHIM_ROOT> <PROFILE_OUT> [REAL_CONDA_DIR]
# Exit:  0 built; 2 on a missing prerequisite.
set -uo pipefail

SHIM_ROOT="${1:?usage: $0 <SHIM_ROOT> <PROFILE_OUT> [REAL_CONDA_DIR]}"
PROFILE_OUT="${2:?usage: see header}"
REAL="${3:-/opt/miniforge3}"
CASCOR_ENV="${JUNIPER_EXP_CASCOR_CONDA:-JuniperCascor1}"
DATA_ENV="${JUNIPER_EXP_DATA_CONDA:-JuniperData}"

PYSPY="${REAL}/envs/${CASCOR_ENV}/bin/py-spy"
REAL_UVICORN="${REAL}/envs/${CASCOR_ENV}/bin/uvicorn"
[[ -x "${PYSPY}" ]] || { echo "shim: py-spy not found at ${PYSPY}" >&2; exit 2; }
[[ -x "${REAL_UVICORN}" ]] || { echo "shim: uvicorn not found at ${REAL_UVICORN}" >&2; exit 2; }

rm -rf "${SHIM_ROOT}"
mkdir -p "${SHIM_ROOT}/envs/${CASCOR_ENV}/bin" "${SHIM_ROOT}/envs/${DATA_ENV}/bin" "${PROFILE_OUT}" || exit 2

# Pass everything except uvicorn straight through, so only the profiled binary is special.
for f in "${REAL}/envs/${CASCOR_ENV}/bin/"*; do
    name="$(basename "${f}")"
    [[ "${name}" == "uvicorn" ]] && continue
    ln -sfn "${f}" "${SHIM_ROOT}/envs/${CASCOR_ENV}/bin/${name}"
done
for f in "${REAL}/envs/${DATA_ENV}/bin/"*; do
    ln -sfn "${f}" "${SHIM_ROOT}/envs/${DATA_ENV}/bin/$(basename "${f}")"
done

cat >"${SHIM_ROOT}/envs/${CASCOR_ENV}/bin/uvicorn" <<SHIM
#!/usr/bin/env bash
# GENERATED by 2026-08-23_pyspy_conda_shim.bash -- do not edit.
#
# --subprocesses is the point: the candidate workers are FORKED from uvicorn, and they are where
# the per-epoch cost lives. --native descends into the C/Rust/Fortran frames, which is the whole
# reason for using a sampling profiler here -- a deterministic Python profiler already showed the
# penalty is NOT in the Python call structure.
#
# --nonblocking is deliberately ABSENT: py-spy refuses to combine it with --native, and native
# frames are the entire point here. Blocking mode pauses the target briefly per sample, which
# costs some overhead -- but it costs BOTH arms the same, and a ratio is what is being measured.
#
# 'exec' so py-spy inherits this shim's pid and stays the direct parent of uvicorn even though the
# launcher nohups and exits.
exec "${PYSPY}" record \\
    --subprocesses --native \\
    --rate "\${JUNIPER_PYSPY_RATE:-100}" \\
    --format raw \\
    --output "${PROFILE_OUT}/service-\$\$.raw" \\
    -- "${REAL_UVICORN}" "\$@"
SHIM
chmod +x "${SHIM_ROOT}/envs/${CASCOR_ENV}/bin/uvicorn"

echo "shim: built ${SHIM_ROOT}"
echo "shim: profiles -> ${PROFILE_OUT}"
echo "shim: use with  JUNIPER_EXP_CONDA_DIR=${SHIM_ROOT}"
