#!/usr/bin/env python3
"""Restore a hand-written requirements.lock header that ``uv pip compile`` overwrote.

Project:     Juniper
Sub-Project: juniper-ml
Application: ad-hoc release tooling
Author:      Paul Calnon
Created:     2026-09-10
Version:     0.1.0
License:     MIT License
Status:      single-use (decision-11 release train, juniper-recurrence app 0.5.0)

Why this exists
---------------
``juniper-recurrence/juniper-recurrence/requirements.lock`` carries a ~30-line hand-written
header (regeneration recipe, the deliberate no-torch rationale, the arm64 wheel pre-flight,
and a KNOWN STALENESS note). ``uv pip compile`` replaces that header with its own two-line
"autogenerated by uv" banner, so every regeneration silently destroys it -- the lock's own
header says "then restore this header" and leaves the how to the operator.

This splices the ORIGINAL header back onto the NEW pin body, replacing the KNOWN STALENESS
paragraph with a supplied resolution note. Both inputs are read from disk; nothing is
resolved or fetched here.

Usage
-----
    python3 util/ad-hoc/2026-09-10_restore_lock_header.py \
        --orig  <path to the pre-regeneration lock> \
        --new   <path to the uv-generated lock, rewritten in place> \
        --note-file <path to the replacement staleness paragraph>

The ``--note-file`` content replaces everything from the first line starting with
``# KNOWN STALENESS`` to the end of the header. Exits non-zero if that marker is absent
or not unique, rather than guessing.
"""

from __future__ import annotations

import argparse
import io
import sys


def first_pin_index(lines: list[str]) -> int:
    """Index of the first non-comment line -- i.e. where the pin body starts."""
    for i, line in enumerate(lines):
        if line.strip() and not line.startswith("#"):
            return i
    raise SystemExit("error: no pin line found (file is all comments?)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--orig", required=True, help="pre-regeneration lock (source of the header)")
    ap.add_argument("--new", required=True, help="uv-generated lock; rewritten in place")
    ap.add_argument("--note-file", required=True, help="replacement for the KNOWN STALENESS paragraph")
    ap.add_argument("--marker", default="# KNOWN STALENESS", help="header line the note replaces from")
    args = ap.parse_args()

    orig = io.open(args.orig, encoding="utf-8").read().splitlines(True)
    new = io.open(args.new, encoding="utf-8").read().splitlines(True)
    note = io.open(args.note_file, encoding="utf-8").read()

    header = orig[: first_pin_index(orig)]
    body = new[first_pin_index(new) :]

    hits = [i for i, line in enumerate(header) if line.startswith(args.marker)]
    if len(hits) != 1:
        raise SystemExit(f"error: marker {args.marker!r} found {len(hits)} times in the header; expected exactly 1")
    header = header[: hits[0]]

    if not note.endswith("\n"):
        note += "\n"

    io.open(args.new, "w", encoding="utf-8").writelines(header + [note] + body)
    print(f"restored: {len(header)} header lines + note + {len(body)} pin-body lines -> {args.new}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
