#!/usr/bin/env python3
"""Emit the seven PR bodies for the main-verify drift-guard fan-out.

Project     : Juniper
Sub-Project : juniper-ml
Application : cross-repo test fan-out (ad-hoc)
Author      : Paul Calnon
License     : MIT License
Created     : 2026-09-08

Seven near-identical PR bodies written by hand is seven chances to paste the wrong
repo's blocker into the wrong repo -- the same transcription-drift argument that
made `port_main_verify_drift_tests.py` a transform rather than a copy. The shared
half lives once here; only the per-repo paragraph varies.
"""

from __future__ import annotations

import sys
from pathlib import Path

SHARED_HEAD = """## Summary

Ports juniper-ml's `main-verify.yml` catch-up-base guard into this repo. Seven repos had
**neither** the juniper-ml original nor the juniper-canopy subset: cascor, cascor-client,
cascor-worker, data, data-client, deploy, recurrence.

## The defect this guards, and why it is silent

`main-verify.yml` resolves its catch-up BASE from the newest run that reached a sequence-safety
**verdict**, not the newest run that was **green**. The signal it reads is an exact step name --
`Assert screens reached a verdict` -- looked up through the jobs API.

Rename that step and **nothing fails**. The resolver matches nothing, silently falls through to the
legacy `status=success` tier, and restores the recurring-red defect while every check stays green.
Measured cost on canopy, 2026-08-31: `main` went permanently red rather than self-clearing, because
a finding froze the base and every later push re-screened the same window; it needed a hand-authored
waiver commit to escape.

Both halves are pinned here, because either assertion alone can drift past the other: the workflow
must define the step, and the resolver must grep for the same literal.

## What landed: the 17-test union

| Source | Tests | Kind |
|---|---|---|
| juniper-ml `tests/test_main_verify_catchup_base.py` | 11 | resolver rehearsal -- extracts the workflow's OWN shell and drives it over a hermetic git fixture + stub `gh` |
| juniper-ml, same file | 5 | static drift pins |
| juniper-canopy `src/tests/regression/…` | 1 | `test_resolver_prefers_the_screened_tier_over_legacy_success` -- its one unique test |
| **total** | **17** | |

Generated by `util/ad-hoc/port_main_verify_drift_tests.py` in juniper-ml, which **transforms** the
reference rather than transcribing it: every seam replacement asserts it matched the expected number
of times, so a reference that moves is a hard error rather than a quietly half-ported file.

## Three deliberate divergences from both references

1. **`SkipTest` becomes a hard failure.** Both references *skip* when the workflow or the resolver
   step cannot be found. This repo has a `main-verify.yml`, so a skip there would mean the file is
   **misplaced** -- and a misplaced guard is silently green, which is the exact shape it exists to
   catch. Skipping on "the verdict step is missing" is worse still: that **is** the drift.
2. **`RedactedEnv` is dropped, not copied.** The original masks a copy of the real environment
   because a subprocess-driving test leaves its env mapping in every failure traceback. This port
   builds a minimal explicit env instead, which removes the exposure rather than masking it -- and
   drops a juniper-ml-only import that does not exist here.
3. **canopy's unique static test is folded in**, giving the union rather than either subset.

## Verification

`util/ad-hoc/verify_main_verify_port.bash` (juniper-ml) proved this port against **this repo's real
`main-verify.yml`**, in both directions:

- **positive** -- 17/17 pass;
- **negative** -- renaming the verdict step by a single character (`verdict` -> `VERDICT`) makes it
  **fail**, `FAILED (failures=2, errors=1)`.

The negative half is not decoration. A guard that cannot fail is worth nothing, and the references'
`SkipTest` behaviour means a bad port is silently green -- so "the suite passed" is not evidence
that this test ran. Confirm it in the CI log by test name.

"""

SHARED_TAIL = """
## Referenced

- juniper-ml `notes/JUNIPER_2026-08-23_JUNIPER-ML_MAIN-VERIFY-CATCHUP-BASE-SCREENED-NOT-GREEN-DESIGN.md`
  -- the design of record, which stays in juniper-ml.
- juniper-ml `prompts/thread-handoff_automated-prompts/HANDOFF_2026-09-07_duplicati-arc-outstanding-work.md`
  §1 item 4 -- the outstanding-work item this closes for this repo.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_011xArV5hGm2evzLB4rNLfj1
"""

REPOS: dict[str, str] = {
    "juniper-cascor-worker": """## In this repo

**Placement**: `tests/test_main_verify_catchup_base.py`. CI runs `python -m pytest tests/` with **no
marker filter**, so the file is collected as-is.

**No dependency change needed** -- PyYAML is already declared in `pyproject.toml`.

## Changed

- `tests/test_main_verify_catchup_base.py` (added)
""",
    "juniper-cascor-client": """## In this repo

**Placement**: `tests/test_main_verify_catchup_base.py`. CI runs `python -m pytest tests/` with **no
marker filter**, so the file is collected as-is.

**Dependency added**: `pyyaml>=6.0.1` in `[project.optional-dependencies] test`. This repo had no
PyYAML anywhere, and without it the new file is an `import yaml` **collection error** -- red CI, not
a silent skip. Worth stating plainly: that failure mode is loud, so the dependency is a correctness
requirement for the PR, not a nicety.

## Changed

- `tests/test_main_verify_catchup_base.py` (added)
- `pyproject.toml` -- `pyyaml>=6.0.1` added to the `test` extra
""",
    "juniper-data-client": """## In this repo

**Placement**: `tests/test_main_verify_catchup_base.py`. CI runs `python -m pytest tests/` with **no
marker filter**, so the file is collected as-is.

**Dependency added**: `pyyaml>=6.0.1` in `[project.optional-dependencies] test`. This repo had no
PyYAML anywhere, and without it the new file is an `import yaml` **collection error** -- red CI, not
a silent skip.

## Changed

- `tests/test_main_verify_catchup_base.py` (added)
- `pyproject.toml` -- `pyyaml>=6.0.1` added to the `test` extra
""",
    "juniper-deploy": """## In this repo

**Placement**: `tests/test_main_verify_catchup_base.py`. CI runs `pytest tests/ -v --tb=short`
(`ci.yml:213`) with **no marker filter**, so the file is collected as-is.

**No dependency change needed, and this corrects the plan.** The outstanding-work item recorded
PyYAML as absent from this repo. It is absent from `pyproject.toml` -- but present in
`requirements-test.txt:6` as `pyyaml>=6.0.3`, which is the path CI installs from. Verified before
writing this PR rather than inherited.

## Changed

- `tests/test_main_verify_catchup_base.py` (added)
""",
    "juniper-cascor": """## In this repo

**Placement**: `src/tests/unit/test_main_verify_catchup_base.py`, **plus** a module-level
`pytestmark = pytest.mark.unit`. Both are required, and the reason is worth stating:

CI runs `python -m pytest -m "unit and not slow" src/tests/unit` (`ci.yml:312-314`) under
`--strict-markers` with no auto-marking conftest. That is **path-scoped as well as marker-filtered**,
so an unmarked file is silently **deselected**, and a file placed anywhere outside `src/tests/unit`
is never collected at all. A new `src/tests/regression/` directory -- the shape the plan sketched --
would have been collected by nothing: present, green, and vacuous.

`unit` is already registered in `pyproject.toml:236`, so `--strict-markers` is satisfied.

**No dependency change needed** -- PyYAML is already declared.

## Changed

- `src/tests/unit/test_main_verify_catchup_base.py` (added)
""",
    "juniper-data": """## In this repo

**Placement**: `juniper_data/tests/unit/test_main_verify_catchup_base.py`, **plus** a module-level
`pytestmark = pytest.mark.unit`. Both are required:

CI runs `python -m pytest -m "unit and not slow" juniper_data/tests/unit` (`ci.yml:286-288`) under
`--strict-markers` with no auto-marking conftest. That is **path-scoped as well as marker-filtered**,
so an unmarked file is silently **deselected** and a file outside `juniper_data/tests/unit` is never
collected at all.

`unit` is already registered in `pyproject.toml:236`, so `--strict-markers` is satisfied.

**No dependency change needed** -- PyYAML is already declared.

## Changed

- `juniper_data/tests/unit/test_main_verify_catchup_base.py` (added)
""",
    "juniper-recurrence": """## In this repo

This repo needed the most care, and none of it was the test file.

**Placement**: `tests/test_main_verify_catchup_base.py` (repo root).

**CI wiring added** to `.github/workflows/sequence-safety.yml`, because nothing else would have run
it:

- This is a **multi-package monorepo with no root `pyproject.toml`**. Its CI is one lane per package
  (`ci-recurrence-app` / `-model` / `-client` / `-bench`), and **no package lane collects the
  top-level `tests/` directory** -- the same reason `memory-budget.yml` runs its own suite by
  explicit `python3 -m unittest` rather than relying on collection.
- Worse, every package lane is **path-filter gated on its own subtree**. A PR that touches only
  `.github/workflows/main-verify.yml` -- which is exactly the change this test exists to catch --
  would skip every one of them. A guard that cannot run on the change it guards is vacuous, so
  placing it in a package lane would have shipped a decoration.

`sequence-safety.yml` is the right host: `pull_request`-triggered on `main`/`develop` with **no path
filter**, it already sets up Python, and its subject matter is precisely the verdict step whose name
this test pins. The step runs **before** the screens, in the house form
(`python3 -m unittest -v tests/test_main_verify_catchup_base.py`) already used by
`memory-budget.yml`.

**Dependency**: `pyyaml>=6.0.1` is pip-installed in that workflow's existing install step. There is
no root `pyproject.toml` to carry it, so it is declared where it is used.

## Changed

- `tests/test_main_verify_catchup_base.py` (added)
- `.github/workflows/sequence-safety.yml` -- `pyyaml` added to the pinned install; new
  `Guard the main-verify verdict-step contract` step before the screens
""",
}


def main() -> int:
    out_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    out_dir.mkdir(parents=True, exist_ok=True)
    for repo, blurb in REPOS.items():
        path = out_dir / f"body_{repo}.md"
        path.write_text(SHARED_HEAD + blurb + SHARED_TAIL, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
